# Production Configuration
server.port=9090

# Database
spring.datasource.url=jdbc:postgresql://ec2-35-154-40-146.ap-south-1.compute.amazonaws.com:5432/ev-vriddhi
spring.datasource.username=postgres
spring.datasource.password=postgres123

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=notifications@evean.net
spring.mail.password=Notifications@alpha
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.root=INFO
logging.level.com.sunbird.serve.volunteering=INFO

# External Service
rc.service.base-url=http://35.154.40.146:8081/api/v1/

# CORS
#spring.web.cors.allowed-origins=http://localhost:9090